# This file contains the configuration for the home (default path) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.


# The large text at the top of the page.
title: "Who is ChainLynx?"

# The text below the title.
about: >
  ChainLynx 8248 is a **FIRST Robotics team** based at Lincoln High School, committed to providing a fun and collaborative environment for students to learn how to design, build, and code robots.
  Through ChainLynx, students gain skills in CAD (Computer Aided Design) software, tool use, business, and leadership that will prepare them for future careers.

# The pictures in the image carousel.
#  The description is shown when the user hovers over the image.
#  The url is the file path relative to the 'public' folder.
pictures:
  - desc: "Pit crew during Bordie Charged 2023"
    url: "/imgs/index/pit_crew_bordie_charged_2023.jpg"
  - desc: "Our robot, 8248, prepared to compete during Bordie Charged 2023"
    url: "/imgs/index/ED101340.jpg"
  - desc: "ChainLynx team members preparing the robot during Bordie Charged 2023"
    url: "/imgs/index/Scan100583.jpg"
  - desc: "Making a quick repair during the Sammamish District Event 2023"
    url: "/imgs/index/DSC_5003.JPG"
  - desc: "Building of the robot during the 2022-2023 season"
    url: "/imgs/index/robot4.jpg"
  - desc: "Kickoff during the 2022-2023 season"
    url: "/imgs/index/2023-01-07 FRC Kickoff 260.JPG"
  - desc: "ChainLynx team members working on the robot during the 2022-2023 season"
    url: "/imgs/index/20230225_154138.jpg"
  - desc: "Watching the 2021-2022 district event"
    url: "/imgs/index/DSC_0056.jpg"