# This file contains the configuration for the home (default path) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.


# The large text at the top of the page.
title: "Our Robot"
# The smaller text below the title.
subtitle: "Our robot is designed and built by our students, with the help of our mentors."

# Sections of the page, each one gets a title and an image gallery.
sections:
  - id: "2022-2023" # This id is used for the table of contents, and for linking to the section. For example, this would be /robot#2022-2023 (NOTE: This value must be unique and cannot contain spaces)
    title: "2022 - 2023 Design" # The title of the section, displayed above the photos
    pictures: # Image to show, this follows the same rules as the pictures section in config/index.yml
      - desc: ""
        url: "/imgs/robot/2022-2023/DSC_4997.JPG"
      - desc: ""
        url: "/imgs/robot/2022-2023/DSC_5087.JPG"
      - desc: ""
        url: "/imgs/robot/2022-2023/DSC_5093.JPG"
      - desc: ""
        url: "/imgs/robot/2022-2023/ED101351.jpg"

  - id: "2021-2022"
    title: "2021 - 2022 Design"
    pictures:
      - desc: ""
        url: "/imgs/robot/2021-2022/IMG_4597.jpg"
      - desc: ""
        url: "/imgs/robot/2021-2022/IMG_4677.jpg"
      - desc: ""
        url: "/imgs/robot/2021-2022/IMG_4739.jpg"
