# This file contains the configuration for the sponsor (/sponsors) page.

# Everything in this file is listen in chronological order to how they appear on the page.
# Both HTML and Markdown are supported in most values.


# The large text at the top of the page.
title: "Our Sponsors"
# The text below the title.
subtitle: >
  Our sponsor’s generous support allows our team to not just exist but thrive. Through their monetary, material, technical, and mentor support, our sponsors 
  empower students to explore their passions through competitive robotics. If interested in sponsoring us, email [business@chainlynx8248.com](mailto:business@chainlynx8248.com).

# The sponsors to display.
#  The name is the name of the sponsor.
#  The url is the link to the sponsor's website.
#  The logo is the file path relative to the 'public' folder.
#  The logo_dark is the file path relative to the 'public' folder. This is used when the user has dark mode enabled.
sponsors:
  - name: "Amazon"
    url: "https://www.amazon.com/"
    logo: "/imgs/sponsors/Amazon_logo.svg"
    logo_dark: "/imgs/sponsors/Amazon-logo-dark.webp"
  - name: "Bayer"
    url: "https://www.bayer.com/en/"
    logo: "/imgs/sponsors/Logo_Bayer.svg"
    logo_dark: "/imgs/sponsors/bayer_dark_mode.png"
  - name: "Leidos"
    url: "https://www.leidos.com/"
    logo: "/imgs/sponsors/Leidos_logo_2013.svg"
    logo_dark: "/imgs/sponsors/Leidos_logo_2013-dark.svg"
  